name: Build Aria2 Windows

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Initialization environment
      run: |
        curl -fsSL https://get.docker.com -o get-docker.sh
        chmod +x get-docker.sh
        ./get-docker.sh
        
    - name: Compile
      run: |
        #sed -ie '19s/i686/x86_64/g' Dockerfile.mingw
        #sed -ie '14s/19.04/20.04/g' Dockerfile.mingw
        #sed -ie '23s/#//g' Dockerfile.mingw
        #sed -ie '29s/libgcrypt11/libssl/g' Dockerfile.mingw
        #sed -ie '19 aENV DEBIAN_FRONTEND noninteractive' Dockerfile.mingw
        sudo docker build -t aria2-mingw - < Dockerfile.mingw
        id=$(sudo docker create aria2-mingw)
        sudo docker cp $id:/aria2/src/aria2c.exe /home/runner/work/Aria2-Pro/Aria2-Pro/aria2c.exe
        sudo docker rm -v $id

    - name: Upload firmware directory
      uses: actions/upload-artifact@main
      with:
        path: /home/runner/work/Aria2-Pro/Aria2-Pro/aria2c.exe
