#
# Copyright (c) 2019-2020 P3TERX <https://p3terx.com>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions
#

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'

env:
  REPO_URL: https://github.com/aria2/aria2.git
  REPO_BRANCH: master
  TZ: Asia/Shanghai
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Initialization environment
      run: |
        echo $PWD
        # sudo apt-get install dialog
        curl -fsSL https://get.docker.com -o get-docker.sh
        chmod +x get-docker.sh
        ./get-docker.sh
        ls
        
    - name: Clone source code
      run: |
        echo $PWD
        git clone $REPO_URL -b $REPO_BRANCH
        ls
        cp -r patch aria2
        cd aria2
        echo $PWD
        ls
        git apply patch/*
